blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('post_list', views.PostListView.as_view(), name='post_list'),
    path('post_create', views.PostCreateView.as_view(), name='post_create'),
    path('post_detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post_update/<int:pk>/', views.PostUpdateView.as_view(),
         name='post_update'),
    path('post_delete/<int:pk>/', views.PostDeleteView.as_view(),
         name='post_delete'),
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField('Title', max_length=150)
    content = models.TextField('Content', max_length=300)
    date = models.DateTimeField('Date', default=timezone.now)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'content')

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse_lazy
from .forms import PostCreateForm
from .models import Post


class PostListView(generic.ListView):
    model = Post

class PostCreateView(generic.CreateView):
    model = Post
    form_class = PostCreateForm 
    success_url = reverse_lazy('blog:post_list')

class PostDetailView(generic.DetailView):
    model = Post

class PostUpdateView(generic.UpdateView):
    model = Post
    form_class = PostCreateForm
    success_url = reverse_lazy('blog:post_list')

class PostDeleteView(generic.DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

blog/templates/base.html
{% load static %}

<!doctype html>
<html lang="ja">

<head>
    <title>Blog App</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
</head>

    <body>
        <div class="wrapper">
            <header>
                <a href="{% url 'blog:post_list' %}">Top</a>
                <a href="{% url 'blog:post_create' %}">PostCreate</a>
            </header>
            <div class="main">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>

</html>

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>Title</th>
            <td>{{ post.title }}</td>
        </tr>
        <tr>
            <th>Content</th>
            <td>{{ post.text | linebreaksbr }}</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ post.date | date:"Y年m月d日" }}</td>
        </tr>
    </table>
    <p>この投稿を削除します。</p>
    <button type="submit" class="delete_btn">Delete</button>
    {% csrf_token %}
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<table class="table">
    <tr>
        <th>Title</th>
        <td>{{ post.title }}</td>
    </tr>
    <tr>
        <th>Content</th>
        <td>{{ post.content | linebreaksbr}}</td>
    </tr>
    <tr>
        <th>Date</th>
        <td>{{ post.date | date:"Y年m月d日" }}</td>
    </tr>
</table>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<p>{{ post.title }}</p>

<form action="" method="POST">
    <table class="table">
        <tr>
            <th>Title</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>Content</th>
            <td>{{ form.content }}</td>
        </tr>
    </table>
    <button type="submit" class="submit_btn">CreatePost</button>
    {% csrf_token %}
</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<table class="table">
    <thead>
        <tr>
            <th><p class="topics">Date</p></th>
            <th><p class="topics">Title</p></th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        {% for post in post_list %}
        <tr>
            <td>{{ post.date | date:"Y年m月d日" }}</td>
            <td><a href="{% url 'blog:post_detail' post.pk %}" class="title_link">{{ post.title }}</a></td>
            <td>
                <a href="{% url 'blog:post_detail' post.pk %}">Detail</a>
            </td>
            <td>
                <a href="{% url 'blog:post_update' post.pk %}">Edit</a>
            </td>
            <td>
                <a href="{% url 'blog:post_delete' post.pk %}">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}